FROM node:12.18 as builder
COPY . /usr/src/app
WORKDIR /usr/app
COPY package*.json  ./

RUN npm install -g @angular/cli@12.2.6
RUN npm install
COPY . /usr/app
RUN ng build --prod

EXPOSE 4000
CMD ["npm", "run", "build:ssr"]
