FROM node:14 as builder
WORKDIR /usr/app
COPY package*.json  ./

RUN npm install -g @angular/cli@12.2.6
RUN npm install
COPY . /usr/app
RUN ng build --prod

FROM nginx
COPY --from=builder /usr/app/dist/* /usr/share/nginx/html/
RUN mkdir -p /usr/share/nginx/html/assets
COPY --from=builder /usr/app/dist/* /usr/share/nginx/html/assets/
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
